### ISSUE TITLE
Question: use of distinct in cluster filtering

### ISSUE THREAD

**Issue by magsol** [mrsqueeze/spark-hash#2]
On [line 32 of LSH.scala](https://github.com/mrsqueeze/spark-hash/blob/master/src/main/scala/com/invincea/spark/hash/LSH.scala#L32), is there any need to invoke `distinct` (just before `zipWithIndex`)? Each vector can only appear in a band at most once anyway; at least, that's how I understand the control flow (still learning Scala).

**Comment by mrsqueeze** [comment]
Prior to distinct(), the sorted list represents the vectors that hash together during one of the bands. Over the course of the banding executions, some (really similar) vectors may hash together multiple times. We sort the vectors and select only the distinct lists as a way to filter out these duplicate occurrences.

Hope this helps!

**Comment by magsol** [comment]
For there to be duplicates in the list, the previous operation on line 28 where the bands are generated would have to have fully duplicated elements, where `((band #, hash of minhash list), vector id)` are precisely identical multiple times in the `model.bands` RDD. As far as I can tell, that isn't possible.

(I'm basically trying to do a PySpark port of LSH as a way to familiarize myself with the process, so please forgive me if I'm missing something obvious)

**Comment by mrsqueeze** [comment]
The map operation preceding distinct() strips out (band #, hash of minhash list) so you just get the result of the groupby (last part of line 28). 

With the sample dataset and the parameters defined in the readme, you'll see that at the end of map() in line 32 and before distinct() there will be a few duplicates.

**Comment by magsol** [comment]
I think my point of confusion is that `distinct` is being invoked on the entire lists of vector ids--that is, if the same **list of vector ids** is duplicated in the RDD, the duplicates are removed. I previously was interpreting distinct() as eliminating duplicate vector ids in a **single** list, e.g. `[1, 1, 2, 3] -> [1, 2, 3]`, when the operation that is actually happening is `[ [1, 2, 3], [1, 2, 3], [4, 5, 6] ] -> [ [1, 2, 3], [4, 5, 6] ]`.

Is this accurate?

**Comment by mrsqueeze** [comment]
distinct is applied to the RDD as a whole so you second case is correct.

**Comment by magsol** [comment]
Awesome, thanks. I may have a working prototype soon for PySpark. I really appreciate your insights.
